GET /rsrc.php/v2/yN/r/CY6jShTMyGt.js
host: static.xx.fbcdn.net

HTTP/1.1 200 OK
access-control-allow-credentials: true
x-content-type-options: nosniff
content-type: application/x-javascript; charset=utf-8
timing-allow-origin: *
cache-control: public, max-age=31536000
expires: Tue, 06 Dec 2016 20:22:26 GMT
content-md5: FTRKDZ2VBu1oO5umzQldww==
last-modified: Mon, 01 Jan 2001 08:00:00 GMT
access-control-allow-origin: *
vary: Accept-Encoding
x-fb-debug: uoc/io1+DJG8GIRjwisEGhi7H5eZgV29PtbkOddT/47Rwyw68YqCxj0qlUnpa2m9KoRPg95MQqeWvWqKkMR8+g==
date: Fri, 18 Dec 2015 20:57:28 GMT
connection: close
content-length: 7624

/*!CK:1237876890!*//*1449519746,*/

if (self.CavalryLogger) { CavalryLogger.start_js(["eScMq"]); }

__d('Base64',[],function a(b,c,d,e,f,g){if(c.__markCompiled)c.__markCompiled();var h='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';function i(m){m=m.charCodeAt(0)<<16|m.charCodeAt(1)<<8|m.charCodeAt(2);return String.fromCharCode(h.charCodeAt(m>>>18),h.charCodeAt(m>>>12&63),h.charCodeAt(m>>>6&63),h.charCodeAt(m&63));}var j='>___?456789:;<=_______'+'\x00\x01\x02\x03\x04\x05\x06\x07\b\t\n\x0b\f\r\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19'+'______\x1a\x1b\x1c\x1d\x1e\x1f !"#$%&\'()*+,-./0123';function k(m){m=j.charCodeAt(m.charCodeAt(0)-43)<<18|j.charCodeAt(m.charCodeAt(1)-43)<<12|j.charCodeAt(m.charCodeAt(2)-43)<<6|j.charCodeAt(m.charCodeAt(3)-43);return String.fromCharCode(m>>>16,m>>>8&255,m&255);}var l={encode:function(m){m=unescape(encodeURI(m));var n=(m.length+2)%3;m=(m+'\0\0'.slice(n)).replace(/[\s\S]{3}/g,i);return m.slice(0,m.length+n-2)+'=='.slice(n);},decode:function(m){m=m.replace(/[^A-Za-z0-9+\/]/g,'');var n=m.length+3&3;m=(m+'AAA'.slice(n)).replace(/..../g,k);m=m.slice(0,m.length+n-3);try{return decodeURIComponent(escape(m));}catch(o){throw new Error('Not valid UTF-8');}},encodeObject:function(m){return l.encode(JSON.stringify(m));},decodeObject:function(m){return JSON.parse(l.decode(m));},encodeNums:function(m){return String.fromCharCode.apply(String,m.map(function(n){return h.charCodeAt((n|-(n>63))&-(n>0)&63);}));}};f.exports=l;},null);
__d('LoggedOutSwitchingLocaleLogger',['BanzaiLogger'],function a(b,c,d,e,f,g,h){if(c.__markCompiled)c.__markCompiled();var i={logOnClick:function(j,k,l,m){if(!j.addEventListener)return;j.addEventListener('click',function(){h.log('LoggedOutSwitchingLocaleLoggerConfig',{old_locale:k,new_locale:l,index:m});});}};f.exports=i;},null);
__d('IntlUtils',['AsyncRequest','Cookie','ReloadPage','goURI'],function a(b,c,d,e,f,g,h,i,j,k){if(c.__markCompiled)c.__markCompiled();var l={setXmode:function(m){new h().setURI('/ajax/intl/save_xmode.php').setData({xmode:m}).setHandler(function(){j.now();}).send();},setAmode:function(m){new h().setURI('/ajax/intl/save_xmode.php').setData({amode:m,app:false}).setHandler(function(){j.now();}).send();},setRmode:function(m){new h().setURI('/ajax/intl/save_xmode.php').setData({rmode:m}).setHandler(function(){j.now();}).send();},setLocale:function(m,n,o,p){if(!o)o=m.options[m.selectedIndex].value;l.saveLocale(o,true,null,n,p);},saveLocale:function(m,n,o,p,q){new h().setURI('/ajax/intl/save_locale.php').setData({aloc:m,source:p,app_only:q}).setHandler(function(r){if(n){j.now();}else k(o);}).send();},setLocaleCookie:function(m,n){i.set('locale',m,7*24*3600000);k(n);}};f.exports=l;},null);
__d('legacy:intl-base',['IntlUtils'],function a(b,c,d,e,f,g,h){if(c.__markCompiled)c.__markCompiled();b.intl_set_xmode=h.setXmode;b.intl_set_amode=h.setAmode;b.intl_set_rmode=h.setRmode;b.intl_set_locale=h.setLocale;b.intl_save_locale=h.saveLocale;b.intl_set_cookie_locale=h.setLocaleCookie;},3);
__d('FormTypeABTester',['Base64','Event'],function a(b,c,d,e,f,g,h,i){if(c.__markCompiled)c.__markCompiled();function j(k){var l=16,m=32,n=65,o=90,p=48,q=57,r=58,s=63,t=91,u=94,v=0,w=0,x=0,y=0,z=[],aa=null,ba=[],ca=[],da=[],ea=[];for(var fa=0;fa<10;fa++){ba.push(0);ca.push(0);}for(var ga=0;ga<10;ga++){ca.push(0);da.push(0);ea.push(0);}var ha=function(ka){var la=window.event?Date.now():ka.timeStamp,ma=window.event?window.event.keyCode:ka.which;ma%=128;if(ma>=n&&ma<=o||ma==m){v++;}else if(ma>=p&&ma<=q){w++;}else if(ma>=r&&ma<=s||ma>=t&&ma<=u){x++;}else y++;z[ma]=la;if(aa){var na=la-aa;if(na>=0&&(ma>=n&&ma<=o||ma==m))if(na<400){ca[Math.floor(na/20)]++;}else if(na<1000){da[Math.floor((na-400)/60)]++;}else if(na<3000)ea[Math.floor((na-1000)/200)]++;}aa=la;},ia=function(ka){var la=window.event?Date.now():ka.timeStamp,ma=window.event?window.event.keyCode:ka.which,na=la-z[ma%128];if(na>=50&&na<250)ba[Math.floor((na-50)/20)]++;},ja=function(ka){var la=Math.max.apply(Math,ka),ma=[];ka.forEach(function(na){ma.push(Math.floor(na*63/(la||1)));});return ma;};this.getDataVect=function(){var ka=ca.concat(da,ea);return ja(ka).concat(ja(ba),[v/2,w/2,x/2,y/2]);};this.getData=function(){return h.encodeNums(this.getDataVect());};i.listen(k,{keyup:ia.bind(this),keydown:ha.bind(this)});}f.exports=j;},null);
__d('DeferredCookie',['Cookie','Map'],function a(b,c,d,e,f,g,h,i){'use strict';if(c.__markCompiled)c.__markCompiled();var j=new i(),k={shouldAddDefaultListener:true,defaultHandler:null,autoFlushCookies:false,addToQueue:function(l,m,n,o,p,q,r){if(this.autoFlushCookies){if(q){h.setIfFirstPartyContext(l,m,n,o,p);}else h.set(l,m,n,o,p);return;}if(j.has(l))return;j.set(l,{name:l,value:m,nMilliSecs:n,path:o,secure:p,firstPartyOnly:q});if(r)this.addDefaultInteractionListener();},flushAllCookies:function(){j.forEach(function(l,m){if(l.firstPartyOnly){h.setIfFirstPartyContext(l.name,l.value,l.nMilliSecs,l.path,l.secure);}else h.set(l.name,l.value,l.nMilliSecs,l.path,l.secure);});this.autoFlushCookies=true;j=new i();this.removeDefaultInteractionListener();},removeDefaultInteractionListener:function(){if(this.defaultHandler){if(window.removeEventListener){window.removeEventListener('click',this.defaultHandler,true);}else if(document.detachEvent)document.detachEvent('onclick',this.defaultHandler);this.defaultHandler=null;}},addDefaultInteractionListener:function(){if(this.shouldAddDefaultListener){this.shouldAddDefaultListener=false;this.defaultHandler=this.baseInteractionHandler.bind(this);if(window.addEventListener){window.addEventListener('click',this.defaultHandler,true);}else if(document.attachEvent)document.attachEvent('onclick',this.defaultHandler);}},baseInteractionHandler:function(){this.flushAllCookies();}};f.exports=k;},null);
__d('LoginFormController',['Event','ge','Button','Cookie','DeferredCookie','FormTypeABTester'],function a(b,c,d,e,f,g,h,i,j,k,l,m){if(c.__markCompiled)c.__markCompiled();g.init=function(n,o,p,q){if(q)var r=new m(n);h.listen(n,'submit',function(){if(q&&n.ab_test_data)n.ab_test_data.value=r.getData();if(window.__cookieReload)window.clearInterval(window.__cookieReload);j.setEnabled(o,false);setTimeout(j.setEnabled.bind(null,o,true),15000);l.flushAllCookies();});var s=i('lgnjs');if(s){var t=Math.floor(Date.now()/1000);s.value=t;}var u=parseInt(k.get('m_ts'),10),v=p!=null;if(u>t-60)v=false;if(v){var w,x=function(){if(k.get('c_user')!=null){window.clearInterval(w);k.set('m_ts',Math.floor(Date.now()/1000),null,'/',false);window.location.href=p;}};w=window.setInterval(x,1000);x();}};},null);
__d("ScreenDimensionsAutoSet",[],function a(b,c,d,e,f,g){if(c.__markCompiled)c.__markCompiled();function h(){if(!window.btoa)return '';var j={w:screen.width,h:screen.height,aw:screen.availWidth,ah:screen.availHeight,c:screen.colorDepth};return btoa(JSON.stringify(j));}var i={setInputValue:function(j){j.value=h();}};f.exports=i;},null);
__d('TimezoneAutoset',['AsyncRequest','emptyFunction'],function a(b,c,d,e,f,g,h,i){if(c.__markCompiled)c.__markCompiled();var j=false;function k(n){var o=new Date(),p=o.getTimezoneOffset()/30,q=o.getTime()/1000,r=Math.round((n-q)/1800),s=Math.round(p+r)%48;if(s==0){return 0;}else if(s>24){s-=Math.ceil(s/48)*48;}else if(s<-28)s+=Math.ceil(s/-48)*48;return s*30;}function l(n,o,p){if(!n||undefined==o)return;if(j)return;j=true;var q=-k(n);if(p||q!=o){var r='/ajax/timezone/update.php';new h().setURI(r).setData({gmt_off:q,is_forced:p}).setErrorHandler(i).setTransportErrorHandler(i).setOption('suppressErrorAlerts',true).send();}}var m={setInputValue:function(n,o){n.value=k(o);},setTimezone:l};f.exports=m;},null);